[project]
name = "dmarc"
version = "0.1.0"
description = "DMARC is a project aimed to automate process of analyzing DMARC report and resolve DMARC issues"
requires-python = ">=3.10, <=3.12"
dependencies = [
    "agentuity>=0.0.105",
    "openai>=1.78.1",
    "slack-sdk==3.35.0",
]
